Controllers/LivroCaixaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Cpr.Web.ViewsModels;
using Microsoft.AspNetCore.Authorization;
using Cpr.Domain;
using Cpr.Domain.LivroCaixa;

namespace Cpr.Web.Controllers
{
    public class LivroCaixaController : Controller
    {

        private readonly ArmazenaLivroCaixa _armazenaLivroCaixa ;
        private readonly IRepository<LivroCaixa> _livroCaixaRepository;
        private readonly IRepository<Categoria> _categoriaRepository;

        public LivroCaixaController(ArmazenaLivroCaixa armazenaLivroCaixa,
            IRepository<LivroCaixa> livroCaixaRepository,
            IRepository<Categoria> categoriaRepository)
        {
            _armazenaLivroCaixa = armazenaLivroCaixa;
            _livroCaixaRepository = livroCaixaRepository;
            _categoriaRepository = categoriaRepository;
        }
      
        private LivroCaixaViewModel LivroCaixaId()
        {
            var livroCaixaViewModel = new LivroCaixaViewModel();
            var categoria = _categoriaRepository.All();
            livroCaixaViewModel.Categorias = categoria.Any()
                ? categoria.Select(c => new CategoriaViewModel { Id = c.Id, Name = c.CategEntradaSaida })
                : new List<CategoriaViewModel>();
            return livroCaixaViewModel;
        }
        public IActionResult Index()
        {           
          
            var livroCaixa = _livroCaixaRepository.All(); 
            if(livroCaixa.Any())
            {    
                var viewsModels = livroCaixa.Select(l => new LivroCaixaViewModel{ Id = l.Id, Tipo = l.Tipo,
                    CategoriaName = l.Categoria.CategEntradaSaida,
                    Data = l.Data, Descricao = l.Descricao, Valor = l.Valor});
                return View(viewsModels);
            }           
            return View();
        }

                  
        public IActionResult Create()
        {  
            var categoriaViewModel = LivroCaixaId();          
            return PartialView(categoriaViewModel);            
        }
        
        [HttpPost]
         public IActionResult Create(LivroCaixaViewModel viewModel)
        {
           
            _armazenaLivroCaixa.ArmazenarCaixa(viewModel.Id, viewModel.Tipo, viewModel.CategoriaId,
             viewModel.Data, viewModel.Descricao, viewModel.Valor);
            return RedirectToAction("Index");
        }

        /*
public IActionResult CreateOrEdit(int id)
{
   var viewModel = new ProductViewModel();
   var categories = _categoryRepository.All();
   viewModel.Categories = categories.Any()
       ? categories.Select(c => new CategoryViewModel {Id = c.Id, Name = c.Name})
       : new List<CategoryViewModel>();
   if (id > 0)
   {
       var product = _productRepository.GetById(id);
       viewModel.Id = product.Id;
       viewModel.Name = product.Name;
       viewModel.CategoryId = product.Category.Id;
       viewModel.Price = product.Price;
       viewModel.StockQuantity = product.StockQuantity;
       return View(viewModel);
   }
   return View(viewModel);

}

[HttpPost]
public IActionResult CreateOrEdit(ProductViewModel viewModel)
{
   _productStorer.Store(viewModel.Id, viewModel.Name, viewModel.CategoryId, viewModel.Price, viewModel.StockQuantity);
   return RedirectToAction("Index");
}
*/
    }
}


Views/LivroCaixa/Create.cshtml
@model Cpr.Web.ViewsModels.LivroCaixaViewModel
@using Cpr.Web.ViewsModels
@{
    ViewData["Title"] = "Nova categoria";
}

<!-- Create Modal-->
<!--  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"> -->
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <h5 class="modal-title" id="ModalLabel">Adicionar Nova Entrada?</h5>
      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="far fa-window-close"></i></span>
      </button>
    </div>    
      <form form id="form" asp-action="Create" asp-controller="LivroCaixa" 
        data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail"
        data-ajax-success="window.location = '/LivroCaixa'">  
        <div class="modal-body">LivroCaixa:
        <!--  <b> @Html.DisplayNameFor(model => model.Descricao) </b> -->
        <!--  <label asp-for="Descricao"></label> -->

        <div class="form-group">
                <label class="col-md-2 control-label">Descrição</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Descricao" >    
                    <span asp-validation-for="Descricao" class="text-danger"></span>
                </div>
                </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Categoria</label>
                <div class="col-md-4">
                    <select class="form-control" asp-for="CategoriaId" asp-items='@(new SelectList(@Model.Categorias,"Id","Name"))'>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Valor</label>
                <div class="col-md-8">
                    <input id="price" type="text" class="form-control" asp-for="Valor" >
                    <span asp-validation-for="Valor" class="text-danger"></span>        
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Tipo</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" asp-for="Tipo" >
                    <span asp-validation-for="Tipo" class="text-danger"></span>    
                </div>
            </div>


             <div class="form-group">
                <label class="col-md-2 control-label">Data</label>
                <div class="col-md-8">
                    <input type="date" class="form-control" asp-for="Data" >
                    <span asp-validation-for="Tipo" class="text-danger"></span>    
                </div>
            </div>




             
        </div>       
        <div class="modal-footer">           
          <input type="hidden"  class="form-control" asp-for="Id">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>     
          <input type="submit" value="Salvar"  class="btn btn-success" />                   
        </div>
      </form> 
    </div>
  </div>
</div>

Views/LivroCaixa/Index.cshtml
@model IEnumerable<Cpr.Web.ViewsModels.LivroCaixaViewModel>
@{
    ViewData["Title"] = "Livro Caixa";
    Layout = "_Layout";
}


        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
         <!-- <h1 class="h3 mb-2 text-gray-800">Tables</h1> -->
        <!--  <p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below. For more information about DataTables, please visit the <a target="_blank" href="https://datatables.net">official DataTables documentation</a>.</p> -->

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Livro Caixa</h6>              
            </div>            
            <div class="card-body">
                
              <div class="table-responsive">
                 <table class="table table-hover table-bordered" id="dataTable" width="100%" cellspacing="0">
                   @if(@Model != null)
                { 
                  <thead>
                    <tr class="table-info"> 
                      <th>@Html.DisplayNameFor(model => model.CategoriaName)</th> 
                      <th>@Html.DisplayNameFor(model => model.Descricao)</th>
                      <th>@Html.DisplayNameFor(model => model.Tipo)</th>
                      <th>@Html.DisplayNameFor(model => model.Data)</th>
                      <th>@Html.DisplayNameFor(model => model.Valor)</th>
                      <th style="text-align: center; width:  8.33%">Editar</th> 
                      <th style="text-align: center; width:  8.33%">Excluir</th>  
                    </tr>
                  </thead>
                  
                  <tfoot>
                    <tr class="table-info">
                      <th></th>
                      <th></th>
                      <th></th>
                      <th class="text-right">Total:</th>
                      <th></th>
                      <th style="text-align: center; width:  8.33%">Editar</th> 
                      <th style="text-align: center; width:  8.33%">Excluir</th>                                            
                    </tr>
                  </tfoot>
                  }
                  <tbody>
                   @if(@Model != null)
                    { 
                      @foreach (var item in Model)
                      {
                      <tr>
                         <td>                          
                          @Html.DisplayFor(modelItem => item.CategoriaName) 
                        </td> 
                        
                        <td>                          
                          @Html.DisplayFor(modelItem => item.Descricao) 
                        </td> 
                        <td> 
                          @(item.Tipo?"Entrada":"Saída")                                                           
                        </td> 
                          <td> 
                          @Html.DisplayFor(modelItem => item.Data)                       
                          </td> 
                         <td>                          
                          @Html.DisplayFor(modelItem => item.Valor) 
                        </td> 
                        <td style="text-align: center;">
                          <a href="#"  title="Editar" data-id="@item.Id" class="btn btn-primary edit" >
                          <i class="far fa-edit"></i></a>                         
                        </td>  
                        <td style="text-align: center;">
                          <a href="#" title="Excluir" data-id="@item.Id" class="btn btn-danger delete" >
                          <i class="fas fa-trash-alt"></i></a>                        
                        </td>                     
                      </tr>               
                      }   
                    }                  
                  </tbody>
                </table>
              </div>
            </div>
          </div>
 <div class="text-right ">  
  <a href="#"  class="btn btn-success create">
  Nova categoria <i class="fas fa-upload"></i></a> 

  <a href="#"  class="btn btn-primary createlivrocaixa">
  Nova entrada <i class="fas fa-upload"></i></a>    
</div> 


<div id="modal" class="modal fade" data-backdrop="static"></div> 

    

@section scripts{
  
<!-- Page level plugins -->
<script src="~/lib/datatables/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables/dataTables.bootstrap4.min.js"></script>
<!-- Page level custom scripts -->
<script src="~/lib/datatables/dataTables-br-edit.js"></script>
<!-- call modal -->
<script src="~/js/modal.js"></script>
<script>
 
 var date = new Date();
 var day = date.getDate();
 var month = date.getMonth() + 1;
 var year = date.getFullYear();

  if (month < 10) month = "0" + month;
    if (day < 10) day = "0" + day;
      var today = year + "-" + month + "-" + day;       
      document.getElementById("Date").value = today;
 
      var mes = month ; 
     var selecionar = '.nav-tabs a[href="#nav-{{tab}}"]'.replace('{{tab}}', mes);
     $(selecionar).tab('show');

    //$(document).ready(function() {
  
//} );
</script>
    }